### ISSUE TITLE
FIX THIS SHIT...... or eLse

### ISSUE THREAD

**Issue by maxerium** [osuAkatsuki/Aika-old#2]
https://github.com/osuAkatsuki/Charlotte/blob/db39833c8d077fb100e73edd2a54c8702567eaf7/Charlotte.py#L198

ok actually mad
put in **osu!std**, thank.ss s s

**Comment by Deallly** [comment]
no.

**Comment by cmyui** [comment]
ur literally an ape

atleast pr it
